export const START_SIGNIN = 'START_SIGNIN';
export const START_SIGNIN_SUCCESS = 'START_SIGNIN_SUCCESS';
export const START_SIGNIN_FAIL = 'START_SIGNIN_FAIL';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';



