export const START_GET_ROOMS = 'START_GET_ROOMS';
export const START_GET_ROOMS_SUCCESS = 'START_GET_ROOMS_SUCCESS';
export const START_GET_ROOMS_FAIL = 'START_GET_ROOMS_FAIL';
export const START_GET_ROOMS_CLEAR = 'START_GET_ROOMS_CLEAR';
